// Run against the isolated fixture: node tests/preview-server.cjs
// PLAYWRIGHT_MODULE may point to an existing Playwright installation.
// BROWSER_CHANNEL defaults to msedge; use chromium for Playwright's bundled browser.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const base = process.env.PREVIEW_URL || 'http://127.0.0.1:8766';
const output = path.join(__dirname, '../test-results/anthill');
fs.mkdirSync(output, { recursive: true });
(async () => {
  const channel = process.env.BROWSER_CHANNEL || 'msedge';
  const browser = await chromium.launch({ headless: true, ...(channel === 'chromium' ? {} : { channel }) });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    const errors = []; page.on('pageerror', e => errors.push(e.message));
    await page.addInitScript(() => localStorage.setItem('fantozzi_user', 'Test mravenisko'));
    const response = await page.request.post(base + '/api/admin/design', { data: { adminPass: 'preview-only', theme: 'anthill' } });
    assert.equal(response.status(), 200);
    await page.clock.install();
    await page.goto(base);
    await page.locator('#ant-dock').waitFor({ state: 'visible' });
    await page.locator('input[name=jedlo]').first().check();
    await page.locator('.item-note-input').first().fill('Bez cibule — zachovať pri hraní');
    await page.locator('#ant-dock [data-action=open]').click();
    assert.equal(await page.locator('#ant-game').evaluate(el => el.open), true);
    await page.locator('#ant-game [data-action=pause]').click();
    const click = action => page.locator('#ant-game [data-action="' + action + '"]').click();
    const tab = key => page.locator('#ant-game [data-tab="' + key + '"]').click();
    const state = () => page.evaluate(() => JSON.parse(localStorage.getItem('fob_anthill_v1')));
    await click('food:fruit'); await click('place-food');
    assert.ok((await state()).foods.some(f => f.type === 'fruit'));
    await click('paths'); assert.equal((await state()).settings.paths, true);
    await click('guide-short'); assert.ok((await state()).guide);
    await tab('build'); await click('build:store'); await click('place-room');
    assert.equal((await state()).rooms.length, 5);
    await page.locator('#ant-room-select').selectOption('4');
    await click('pause-room'); assert.equal((await state()).rooms[4].paused, true);
    await click('pause-room');
    await tab('colony'); await page.locator('#ant-ant-select').selectOption('0');
    await page.locator('#ant-name').fill('<Mimi & Lili>'); await click('rename'); await click('favorite');
    assert.equal((await state()).ants[0].name, '<Mimi & Lili>');
    assert.equal(await page.locator('#ant-detail h4').textContent(), '<Mimi & Lili>');
    await click('follow'); await click('follow-off'); await click('center');
    await click('role:gather:-1'); await click('role:dig:1');
    assert.equal((await state()).auto, false);
    await click('auto');
    await tab('settings'); await click('bridge'); await click('rock');
    assert.equal((await state()).bridge, true); assert.equal((await state()).rock, 440);
    await click('reset'); await click('cancel-reset'); assert.equal((await state()).rooms.length, 5);
    await click('pause');
    await page.clock.runFor(15000);
    await click('pause');
    const running = await state(); assert.ok(running.time > 10); assert.ok(running.ants.some(a => a.x !== 600));
    await tab('food'); await click('cancel');
    await page.screenshot({ path: path.join(output, 'desktop.png') });
    await click('close');
    await page.locator('#ant-dock').waitFor({state:'visible'});
    assert.equal(await page.locator('input[name=jedlo]').first().isChecked(), true);
    assert.equal(await page.locator('.item-note-input').first().inputValue(), 'Bez cibule — zachovať pri hraní');
    assert.equal(await page.locator('#ant-background').evaluate(el => getComputedStyle(el).pointerEvents), 'none');
    await page.screenshot({ path: path.join(output, 'background.png') });
    await page.reload(); await page.locator('#ant-dock [data-action=open]').click();
    await tab('colony'); await page.locator('#ant-ant-select').selectOption('0');
    assert.equal(await page.locator('#ant-name').inputValue(), '<Mimi & Lili>');
    await page.evaluate(() => applyTheme('blocks'));
    assert.equal(await page.locator('#ant-game').evaluate(el => el.open), false);
    assert.equal(await page.locator('#ant-dock').isVisible(), false);
    assert.equal(await page.locator('#ant-background').isVisible(), false);
    const before = (await state()).time; await page.clock.runFor(3000); assert.equal((await state()).time, before);
    await page.evaluate(() => applyTheme('anthill'));
    await page.locator('#ant-dock [data-action=open]').click();
    await click('pause');
    await page.evaluate(() => { Object.defineProperty(document, 'hidden', { value: true, configurable: true }); document.dispatchEvent(new Event('visibilitychange')); });
    const hiddenAt = (await state()).time; await page.clock.runFor(3000);
    await click('pause'); assert.equal((await state()).time, hiddenAt);
    await page.evaluate(() => { Object.defineProperty(document, 'hidden', { value: false, configurable: true }); document.dispatchEvent(new Event('visibilitychange')); });
    assert.deepEqual(errors, []);
    await page.close();

    const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, reducedMotion: 'reduce' });
    mobile.on('pageerror', e => errors.push(e.message));
    await mobile.goto(base); await mobile.locator('#ant-dock').waitFor({state:'visible'});
    await mobile.locator('#ant-dock [data-action=open]').tap();
    await mobile.locator('#ant-game [data-action="food:cheese"]').tap();
    await mobile.locator('#ant-game [data-action=place-food]').tap();
    assert.ok(await mobile.locator('#ant-status').textContent());
    assert.equal(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await mobile.screenshot({path:path.join(output,'mobile.png')});
    await mobile.locator('#ant-game [data-action=close]').tap();
    await mobile.locator('#ant-dock [data-action=hide]').tap();
    assert.equal(await mobile.locator('#ant-background').isVisible(), false);
    await mobile.locator('#ant-dock [data-action=hide]').tap();
    assert.equal(await mobile.locator('#ant-background').isVisible(), true);
    await mobile.screenshot({path:path.join(output,'mobile-background.png')});
    assert.deepEqual(errors, []);
    console.log('PASS: desktop/mobile interactions, simulation, persistence, theme cleanup, hidden-tab suspension, reduced motion, and no browser errors.');
  } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exitCode = 1; });
