// Run with the isolated tests/preview-server.cjs, never production.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const base = process.env.PREVIEW_URL || 'http://127.0.0.1:8766';
const output = path.join(__dirname, '../test-results/anthill');
fs.mkdirSync(output, { recursive: true });
(async () => {
  const browser = await chromium.launch({ headless: true, channel: process.env.BROWSER_CHANNEL || 'msedge' });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    const errors = []; page.on('pageerror', e => errors.push(e.message));
    await page.addInitScript(() => localStorage.setItem('fantozzi_user', 'Test mravenisko'));
    const response = await page.request.post(base + '/api/admin/design', { data: { adminPass: 'preview-only', theme: 'anthill' } });
    assert.equal(response.status(), 200);
    await page.clock.install(); await page.goto(base);
    await page.locator('#ant-dock').waitFor({ state: 'visible' });
    assert.equal(await page.locator('#ant-dock').evaluate(el => el.open), false);
    assert.equal(await page.locator('#ant-game').evaluate(el => el.open), false);
    assert.equal(await page.locator('#ant-background').evaluate(el => getComputedStyle(el).pointerEvents), 'none');
    await page.locator('input[name=jedlo]').first().check();
    await page.locator('.item-note-input').first().fill('Bez cibule');
    await page.clock.runFor(12000);
    const state = () => page.evaluate(() => JSON.parse(localStorage.getItem('fob_anthill_v1')));
    const living = await state(); assert.ok(living.time > 8); assert.ok(living.foods.length > 0); assert.equal(living.auto, true);
    await page.screenshot({ path: path.join(output, 'background.png') });
    await page.locator('#ant-dock summary').click();
    await page.locator('#ant-dock [data-action=open]').click();
    assert.equal(await page.locator('#ant-game').evaluate(el => el.open), true);
    assert.equal(await page.locator('#ant-game [data-tab]').count(), 0);
    await page.locator('#ant-game [data-action=zoom-in]').click();
    await page.locator('#ant-game [data-action=center]').click();
    await page.screenshot({ path: path.join(output, 'desktop.png') });
    await page.locator('#ant-game [data-action=close]').click();
    assert.equal(await page.locator('input[name=jedlo]').first().isChecked(), true);
    assert.equal(await page.locator('.item-note-input').first().inputValue(), 'Bez cibule');
    await page.locator('#ant-dock summary').click();
    await page.locator('#ant-dock [data-action=pause]').click();
    const paused = (await state()).time; await page.clock.runFor(2000);
    await page.locator('#ant-dock [data-action=hide]').click(); assert.equal((await state()).time, paused);
    assert.equal(await page.locator('#ant-background').isVisible(), false);
    await page.locator('#ant-dock [data-action=hide]').click();
    await page.locator('#ant-dock [data-action=pause]').click();
    await page.evaluate(() => applyTheme('blocks'));
    assert.equal(await page.locator('#ant-dock').isVisible(), false);
    const stopped = (await state()).time; await page.clock.runFor(2000); assert.equal((await state()).time, stopped);
    await page.evaluate(() => applyTheme('anthill'));
    await page.evaluate(() => { Object.defineProperty(document, 'hidden', { value: true, configurable: true }); document.dispatchEvent(new Event('visibilitychange')); });
    const hidden = (await state()).time; await page.clock.runFor(2000);
    await page.locator('#ant-dock [data-action=pause]').click(); assert.equal((await state()).time, hidden);
    await page.reload(); assert.equal((await state()).settings.paused, true);
    assert.deepEqual(errors, []); await page.close();
    const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, reducedMotion: 'reduce' });
    mobile.on('pageerror', e => errors.push(e.message));
    await mobile.goto(base); await mobile.locator('#ant-dock').waitFor({ state: 'visible' });
    assert.equal(await mobile.locator('#ant-dock').evaluate(el => el.open), false);
    assert.equal(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await mobile.screenshot({ path: path.join(output, 'mobile-background.png') });
    await mobile.locator('#ant-dock summary').tap(); await mobile.locator('#ant-dock [data-action=open]').tap();
    await mobile.screenshot({ path: path.join(output, 'mobile.png') });
    assert.equal(await mobile.locator('#ant-game').evaluate(el => el.open), true);
    assert.deepEqual(errors, []);
    console.log('PASS: autonomous background without opening the observer, unobstructed ordering, compact controls, pause, persistence, mobile, theme cleanup and hidden-tab suspension.');
  } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exitCode = 1; });
